# Generated by Django 4.2.5 on 2023-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesichat',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
