# Generated by Django 4.2.5 on 2023-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_sesichat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesichat',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
