# Generated by Django 4.2.5 on 2023-09-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_sesichat_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesichat',
            name='session_name',
        ),
    ]
