# Generated by Django 4.2.5 on 2023-09-25 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_sesichat_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default=datetime.datetime(2023, 9, 25, 17, 20, 38, 919686, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
