# Generated by Django 4.2.5 on 2023-09-26 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.CharField(max_length=255)),
                ('kode_mata_kuliah', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('jurusan', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=100)),
                ('jam_mulai', models.TimeField()),
                ('jam_berakhir', models.TimeField()),
                ('kode_ruangan', models.CharField(max_length=10)),
                ('metode_pembelajaran', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(limit_choices_to={'role': 'Dosen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
