# Generated by Django 4.2.5 on 2023-09-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_courseschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSchedule',
            new_name='JadwalMengajar',
        ),
    ]
