# Generated by Django 4.2.5 on 2023-09-26 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jadwalmengajar_metode_pembelajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalmengajar',
            name='hari',
            field=models.CharField(choices=[('SENIN', 'SENIN'), ('SELASA', 'SELASA'), ('RABU', 'RABU'), ('KAMIS', 'KAMIS'), ('JUMAT', 'JUMAT'), ('SABTU', 'SABTU')], default=datetime.datetime(2023, 9, 26, 0, 55, 52, 129782, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
