# Generated by Django 4.2.5 on 2023-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jadwalmengajar_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalmengajar',
            name='hari',
            field=models.CharField(choices=[('Monday', 'SENIN'), ('Tuesday', 'SELASA'), ('Wednesday', 'RABU'), ('Thursday', 'KAMIS'), ('Friday', 'JUMAT'), ('Saturday', 'SABTU')], max_length=100),
        ),
    ]
