# Generated by Django 4.2.5 on 2023-09-30 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionroom',
            name='cover',
            field=models.ImageField(default=datetime.datetime(2023, 9, 30, 0, 35, 6, 537432, tzinfo=datetime.timezone.utc), upload_to='coverGroup'),
            preserve_default=False,
        ),
    ]
